---
- name: "Download kibana's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm"
    dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
    validate_certs: false
  register: download_kibana
  until: download_kibana is succeeded
      
   