---
- name: "Download kibana's deb"
  get_url:
    url: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-{{ kibana_version }}-amd64.deb"
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0755
    validate_certs: false
  register: download_kibana
  until: download_kibana is succeeded
      
   