---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Check that the kibana.yml exists
    stat:
      path: /etc/kibana/kibana.yml
    register: stat_result
    failed_when: not stat_result.stat.exists
  - name: get fact
    service_facts:
  - name: Check if kibana is running 
    assert:
      that:
        ansible_facts.services["kibana.service"].state == "running"
      fail_msg: "Kibana service not running"
      success_msg: "Kibana service running"
