---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Check that the kibana.yml exists
    stat:
      path: /etc/kibana/kibana.yml
    register: stat_result
    failed_when: not stat_result.stat.exists
  - name: get fact
    service_facts:
  - name: Check if kibana service is running 
    assert:
      that:
        ansible_facts.services["kibana.service"].state == "running"
      fail_msg: "Kibana service not running"
      success_msg: "Kibana service running"
  
  # - name: Check that you can connect (GET) to a page and it returns a status 200
  #   uri:
  #     url: http://localhost:5601
  #     timeout: 15
  #   register: kibana_state
  
  # - name: debug
  #   debug: var=kibana_state


  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
      url: http://localhost:5601
      timeout: 30
    register: kibana_state
    until: kibana_state.status == 200
    retries: 10
    delay: 10
# 
  - name: Check if kibana service is running 
    assert:
      that:
        - kibana_state.status == 200
      fail_msg: "Kibana connect (GET) not returns a status 200"
      success_msg: "Kibana connect (GET) returns a status 200"

