dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7
    hostname: centos
    image: mpaivabarbosa/molecule-systemd-centos:7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:  
  test_sequence:
  - destroy
  - create
  - converge
  - destroy
